

function getRandomNumber() {
    return Math.floor(Math.random() * 100) + 1;
}

// This function prompts the player to enter their guess and returns it as an integer
let getPlayerGuess = () => {
  // Prompt the player to enter their guess
  let playerGuess = prompt("Enter your guess as an integer number Between numbers 1 and 100:");
  // return the player's guess as an integer
  return parseInt(playerGuess);
}

// This function checks the player's guess against the random number and provides feedback
let checkGuess = function(playerGuess, randomNumber, attempts) {
  
  /*
  * Parameters:
  * playerGuess: the player's guess as an integer
  * randomNumber: the random number generated by the game as an integer number between 1 and 100
  * attempts: the number of attempts the player has made so far as an integer
  * 
  * 
  * This function compares the player's guess to the random number and provides feedback on 
  * whether the guess is correct, too low, or too high. 
  * It provides feedback on how many attempts are left. The player has a maximum of 10 attempts to guess the number correctly.
  */

  if (playerGuess === randomNumber) {
    alert("Congratulations! You guessed the number in " + attempts + " attempts!");
  } else if (playerGuess < randomNumber) {
    alert("Too low! Try again. You have " + (10 - attempts) + " attempts left.");
  } else {
    alert("Too high! Try again. You have " + (10 - attempts) + " attempts left.");
  }

}

const game = () => {
  // Generate a random number between 1 and 100
  alert("Welcome to the Number Guessing Game! You have 10 attempts to guess the number between 1 and 100.");
  const randomNumber = getRandomNumber();
  console.log("The random number is: " + randomNumber); // For testing purposes, you can remove this line in production
  let attempts = 0;
  let number_guessed = getPlayerGuess();

  while (attempts < 10 && number_guessed !== randomNumber) {
    attempts++;
    checkGuess(number_guessed, randomNumber, attempts);
    if (number_guessed === randomNumber) {
      break;
    }
    number_guessed = getPlayerGuess();
  }

}
game();