let gameOver = false;
let error = false;
let score = 0;

const getRandomNumber = function () {
    return Math.floor(Math.random() * 100) + 1;
}

// This function prompts the player to enter their guess and returns it as an integer
const getPlayerGuess = () => {
  // Prompt the player to enter their guess
  let playerGuess = prompt("Enter your guess as an integer number Between numbers 1 and 100:");

  if (playerGuess === null) {
    if(confirm("Do you want to exit the game?")){
      console.log("Thanks for playing! Goodbye!");
      gameOver = true;
      return;
    } 
  } else if (isNaN(playerGuess) || playerGuess < 1 || playerGuess > 100) {
    alert("Invalid input! Please enter an integer number between 1 and 100.");
    console.log("Invalid input! Please enter an integer number between 1 and 100.");
    error = true;
    return;
  }  
  // return the player's guess as an integer
  return parseInt(playerGuess);
}

// This function checks the player's guess against the random number and provides feedback
const checkGuess = function(playerGuess, randomNumber, attempts) {
  
  /*
  * Parameters:
  * playerGuess: the player's guess as an integer
  * randomNumber: the random number generated by the game as an integer number between 1 and 100
  * attempts: the number of attempts the player has made so far as an integer
  * 
  * 
  * This function compares the player's guess to the random number and provides feedback on 
  * whether the guess is correct, too low, or too high. 
  * It provides feedback on how many attempts are left. The player has a maximum of 10 attempts to guess the number correctly.
  */

  if (playerGuess === randomNumber) {
    alert("Congratulations! You guessed the number in " + attempts + " attempts!" + " Your score is " + (11-attempts)*10 + ".");
    console.log("Congratulations! You guessed the number in " + attempts + " attempts!" + " Your score is " + (11-attempts)*10 + ".");
    gameOver = true;
  } else if (playerGuess < randomNumber) {
    alert("Too low! Try again. You have " + (10 - attempts) + " attempts left.");
    console.log("Too low! Try again. You have " + (10 - attempts) + " attempts left.");
  } else if (playerGuess > randomNumber) {
    alert("Too high! Try again. You have " + (10 - attempts) + " attempts left.");
    console.log("Too high! Try again. You have " + (10 - attempts) + " attempts left.");
  } 
  // else {
  //   alert("Invalid input! Please enter an integer number between 1 and 100.");
  // }
}

const game = () => {
  alert("Welcome to the Number Guessing Game! You have 10 attempts to guess the number between 1 and 100.");
  console.log("Welcome to the Number Guessing Game! You have 10 attempts to guess the number between 1 and 100.");
  const randomNumber = getRandomNumber();
  let attempts = 0;

  while (attempts < 10 && !gameOver) {
    let number_guessed = getPlayerGuess();

    if (error) {
      error = false;
      continue;
    }

    attempts++;
    checkGuess(number_guessed, randomNumber, attempts);
  }

  if (attempts >= 10 && !gameOver) {
    alert("Game over! You ran out of attempts. The number was " + randomNumber + ".");
    console.log("Game over! You ran out of attempts. The number was " + randomNumber + ".");
  }
}


game();